### ISSUE TITLE
Show loading spinner while the data is loading.

### ISSUE THREAD

**Issue by anuraghazra** [bradgarropy/adobe-lunch#44]
Hi @bradgarropy 

It's just my opinion as an end-user, that i feel like the UI is stuck because after i click the Frown button i don't get any instant feedback from the UI (like a loading/progress bar). So it would be nice to have one i guess.

**Comment by bradgarropy** [comment]
This site is served statically. Beyond the venue's image, there's nothing that the page is fetching.

I just tried throttling the Network to `Slow 3G` and found that the page load times were still very snappy. Could you maybe send over a gif illustrating a long wait period? I'm having trouble reproducing on my end, and finding it tough to justify the need for a spinner.

**Comment by anuraghazra** [comment]
Yeah, you are right @bradgarropy, it's snappy enough.. although it was just my personal opinion as a user.

**Comment by bradgarropy** [comment]
Thanks for the feedback!
